baseURL = 'https://blog.messfar.com/'
languageCode = 'zh-tw'
title = "York Lin's blog"
theme = "hugo-theme-stack"

enable_site_search = true

[services.disqus]
  shortname = 'superj80820'

[params]
  mainSections = [ "post" ]
  featuredImageField = "image"
  rssFullContent = true
  [[params.widgets.homepage]]
    type = "search"
  [[params.widgets.homepage]]
    type = "archives"
  [[params.widgets.homepage]]
    type = "tag-cloud"
  [[params.widgets.page]]
    type = "toc"
  [params.article]
    toc = true
    readingTime = true
  [params.sidebar]
    emoji = "⚾"
  [params.sidebar.avatar]
    enabled = true
    local = true
    src = "avatar.jpg"
  [params.comments]
    enabled = true
    provider = "disqus"

# [menus]
#   [[menus.main]]
#     name = 'Golang 設計模式'
#     url = '/posts/design-patterns-1-introduction'
#     weight = 10
#   [[menus.main]]
#     name = 'Golang 系統設計'
#     url = '/posts/system-design-1-introduction'
#     weight = 11
#   [[menus.main]]
#     name = '文章分類'
#     url = "/tags"
#     weight = 20
#   [[menus.main]]
#     name = '關於我'
#     pageRef = '/about-me'
#     weight = 30